name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform-android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Usamos Gradle global en lugar de ./gradlew
      - name: Build with Gradle
        run: gradle build

      - name: Run Lint
        run: gradle lint

      - name: Run Unit Tests
        run: gradle test

